debug: True
verbose: False
path_topic: ~path
optimized_path_topic: ~optimized_path_topic
twist_topic: ~twist
smooth_twist_topic: ~smooth_twist
lookahead_twist_topic: /path_planning_and_following/twist
projected_goal_topic: ~projected_goal

# topics to construct the observation space
joint_actions_topic: /anymal_low_level_controller/actuator_readings
state_estimator_topic: /state_estimator/anymal_state
gridmap_topic: /elevation_mapping/elevation_map_raw  # this assumes the https://github.com/leggedrobotics/elevation_mapping_cupy is used
gridmap_layer: elevation
goal_topic:  /mp_waypoint

# model path
model_path: <path_to_model>

remove_torque: True

replan_frequency: 10

base: base
odom: odom
map: map

# options to change the planned paths
restricted_forward_motion_range: [-0.1, 0.5]
restricted_sideward_motion_range: [-0.1, 0.1]
# restricted_rotation_range: [-0.33, 0.33]
height_scan_dilution: False

use_dynamic_reconfigure: False
invert_twist: False
publish_twist: True
spline_smooth_n: 3
lookahead_n: 2
do_not_publish_if_reached: True
do_not_publish_distance_offset: 0.5
do_not_publish_heading_offset: 2.0

# adjustments for plots
add_path_to_plan: False
predict_path_without_plan: False
