[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Forward Dynamics Model"
author = "Pascal Roth"
maintainer = "Pascal Roth"
description="Learned Forward Dynamics Model for Local Planning of Mobile"
repository = "https://github.com/leggedrobotics/forward_dynamics_model.git"
keywords = ["robotics", "planning", "dynamics_model"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
"nav_collectors" = {}
"nav_tasks" = {}

[[python.module]]
name = "ext_template"
