[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Forward Dynamics Model"
description="Learned Forward Dynamics Model for Local Planning of Mobile Robots"
authors =["Pascal Roth"]
repository = "https://github.com/leggedrobotics/forward_dynamics_model.git"
keywords = ["robotics", "planning", "dynamics_model"]
category = "robotics"
readme  = "docs/README.md"

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}
"nav_collectors" = {}
"nav_tasks" = {}

# Main python module this extension provides.
[[python.module]]
name = "fdm"
